condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true